squeezy/controllers/main.py
import logging
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, jsonify, make_response
from json import dumps
from flask_security import login_required, logout_user, current_user
from squeezy.forms.settings import SettingsForm
from squeezy.forms.file import FileForm
from squeezy.models.settings import Settings
from squeezy.models.acl import AccessControlList
from squeezy.service.basic_settings import BasicSettingsService
from squeezy.service.squeezy import SqueezyService, SqueezyServiceFileFormatError, SqueezyServiceFileInUseError, SqueezySquidReconfigureError
from squeezy.models.file import File
from squeezy.helpers.acl_types import ACL_TYPES
from squeezy.helpers.directive_types import DIRECTIVE_TYPES
main_module = Blueprint('main', __name__)


@main_module.route("/")
@login_required
def root():
    return render_template("index.html.j2", user=current_user)


@main_module.route("/logs")
@login_required
def logs():
    logs = SqueezyService().get_logs()
    return render_template("logs.html.j2", user=current_user, logs=logs)


@main_module.route("/logs/download/<name>")
@login_required
def download_log(name: str):
    logs = SqueezyService().get_logs()
    try:
        log = logs[name]
    except KeyError as e:
        flash("Unknown log requested")
        return redirect(url_for("main.logs"))
    response = make_response(log)
    response.content_type = "text/plain"
    return response


@main_module.route("/users")
@login_required
def users():
    return render_template("users.html.j2", user=current_user)


@main_module.route("/logout", methods=["POST"])
@login_required
def logout():
    logging.info(f"About to log out user {current_user.email}")
    logout_user()
    return redirect(url_for('main.root'))


@main_module.route("/basic", methods=["GET", "POST"])
@login_required
def basic_settings():
    settings = dict([(setting.key, setting.value)
                    for setting in Settings.query.all()])
    form = SettingsForm(data=settings)
    if form.validate_on_submit():
        try:
            BasicSettingsService().updateSettings(form)
        except Exception as e:
            flash(f"Unknown Error: {e.args[0]}")
        return redirect(url_for('main.basic_settings'))
    return render_template("basic-settings.html.j2", user=current_user, form=form)


@main_module.route("/files", methods=["GET", "POST"])
@login_required
def files():
    form = FileForm()
    files = File.query.all()
    if form.validate_on_submit():
        try:
            logging.info(
                f"handle_file_upload: {form.label.data} / {form.file.data.filename} / {form.file.data.content_length} / {form.file.data.content_type} ")
            SqueezyService().handle_file_upload(form)
        except SqueezyServiceFileFormatError as e:
            flash(f"Text file expected, got: {form.file.data.content_type}")
            logging.error(
                f"FileFormatError for handle_file_upload: {form.label.data} / {form.file.data.filename} / {form.file.data.content_length} / {form.file.data.content_type}")
        except Exception as e:
            flash(f"Unknown Error: {e.args[0]}")
        return redirect(url_for('main.files'))
    return render_template("files.html.j2", user=current_user, form=form, files=files)


@main_module.route("/files/<id>", methods=["GET", "POST"])
@login_required
def file(id: int):
    try:
        file = File.query.filter_by(id=id).first()
        content = SqueezyService().handle_file_read(file)
    except Exception as e:
        flash(f"Unhandled exception: {e.args}")
        logging.error(f"Error reading file: {e.args}")
        return redirect(url_for("main.root"))
    return render_template("file.html.j2", user=current_user, file=file, content=content)


@main_module.route("/files/delete", methods=["POST"])
@login_required
def file_delete():
    try:
        id = request.args.get("id")
        file = File.query.filter_by(id=id).first()
        SqueezyService().handle_file_delete(file)
    except SqueezyServiceFileInUseError as e:
        flash(f"Unhandled exception: {e.args}")
        return redirect(url_for("main.files"))
    except Exception as e:
        flash(f"Unhandled exception: {e.args}")
        return redirect(url_for("main.root"))
    return redirect(url_for('main.files'))


@main_module.route("/acls", methods=["GET", "POST"])
@login_required
def acls():
    return render_template("acls.html.j2", user=current_user, types=dumps(ACL_TYPES).replace("\"", "\\\""))


@main_module.route("/directives", methods=["GET"])
@login_required
def access_directives():
    return render_template("directives.html.j2", user=current_user, types=dumps(DIRECTIVE_TYPES).replace("\"", "\\\""))


@main_module.route("/apply", methods=["POST"])
@login_required
def apply_config():
    try:
        SqueezyService().apply_config()
    except Exception as e:
        flash(f"Unhandled exception: {e.args}")
        return redirect(url_for("main.root"))
    return redirect(url_for("main.get_config"))


@main_module.route("/config", methods=["GET"])
@login_required
def get_config():
    try:
        content = SqueezyService().get_config()
    except Exception as e:
        flash(f"Unhandled exception: {e.args}")
        return redirect(url_for("main.root"))
    return render_template("config.html.j2", user=current_user, content=content)


@main_module.route("/reconfigure", methods=["POST"])
@login_required
def reconfigure_squid():
    try:
        SqueezyService().reload_service()
    except SqueezySquidReconfigureError as e:
        flash(e.args[0])
        return redirect(url_for("main.get_config"))
    flash("Reload successeful!")
    return redirect(url_for("main.get_config"))

templates/acls.html.j2
{% extends "base.html.j2" %}

{% block app %}
<div class="container">
    <div class="row border rounded padding-1 m-2" id="acl-editor">

    </div>
</div>
{% endblock app %}

{% block title %}
{{ super() }}: Access Control Lists
{% endblock title %}

{% block javascripts %}
{{ super() }}
<script>
    const acl_types = JSON.parse("{{ types }}");
</script>
<script defer src="/static/dist/aclEditor.bundle.js"></script>
{% endblock javascripts %}

templates/apply.html.j2
{% extends "base.html.j2" %}

{% block app %}
<div class="container">
    <div class="row align-items-center justify-content-center">
        <h1>Configuration applied!</h1>
    </div>
    <div class="row">
        <div class="col">
            <h1>Current config</h1>
            <pre class="file-view">
{{ content }}
            </pre>
        </div>
    </div>
</div>
{% endblock app %}

{% block title %}
{{ super() }}: File View
{% endblock title %}

templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
<head>
{% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
    Squeezy{% endblock title %}</title>
    {% block styles %}
    <link rel="stylesheet" href="/static/dist/main.css">
    {% endblock styles %}
    {% block javascripts %}
    <script defer src="/static/dist/main.bundle.js"></script>
    {% endblock javascripts %}
{% endblock head %}
</head>
<body>
    <div class="container-fluid">
        <div class="navbar-squeezy">
            <p id="title" class="text-center">
                <a class="navbar-brand" href="{{ url_for('main.root')}}">Squeezy</a>
            </p>
            <div id="logout" class="border rounded">
                <div class="text-end">
                    {% if user %}
                    <form action="{{ url_for('main.logout')}}" method="post">
                    {{ user.email }} <input class="btn btn-sm btn-danger" type="submit" value="LOGOUT">
                    </form>
                    {% endif %}
                </div>
            </div>
            <nav class="navbar sidebar">
                {% block sidebar %}
                {% include "partials/sidebar.html.j2" %}
                {% endblock sidebar %}
            </nav>
        </div>
        <div class="row">
            <div class="col-12">
                {% block app %}
                {% endblock app %}
            </div>
        </div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="list-unstyled flashes border rounded alert alert-secondary p-2">    
                {% for message in messages %}
                    <li class="alert alert-danger mb-1"><pre>{{ message }}</pre></li>
                {% endfor %}
            </ul>        
        {% endif %}
        {% endwith %}
    </div>
</body>
</html>

templates/basic-settings.html.j2
{% extends "base.html.j2" %}

{% block app %}
<div class="container">
    <div class="row align-items-center justify-content-center">
        <h1>Basic Settings</h1>
    </div>
    <form action="{{url_for('main.basic_settings')}}" method="post">
        {{ form.csrf_token }}
        {{ form.http_port.label }} {{ form.http_port }}
        <input type="submit" value="Save">
    </form>
</div>
{% endblock app %}

{% block title %}
{{ super() }}: Basic Settings
{% endblock title %}

templates/config.html.j2
{% extends "base.html.j2" %}

{% block app %}
<div class="container">
    <div class="row align-items-center justify-content-center mb-2">
        <h1>Configuration Viewer</h1>
    </div>
    <div class="row">
        <div class="col">
            <h1>Current configuration: </h1>
            <pre class="file-view">
{{ content }}
            </pre>
        </div>
    </div>
    <div class="row">
        <div class="col-1">
            <form action="{{url_for('main.reconfigure_squid')}}" method="post">
            <input type="submit" class="btn btn-danger" value="Reload Service">
            </form>
        </div>
    </div>
</div>
{% endblock app %}

{% block title %}
{{ super() }}: File View
{% endblock title %}

templates/directives.html.j2
{% extends "base.html.j2" %}

{% block app %}
<div class="container">
    <div class="row border rounded padding-1 m-2" id="directive-editor">

    </div>
</div>
{% endblock app %}

{% block title %}
{{ super() }}: Access Directives
{% endblock title %}

{% block javascripts %}
{{ super() }}
<script>
    const directive_types = JSON.parse("{{ types }}");
</script>
<script defer src="/static/dist/directiveEditor.bundle.js"></script>
{% endblock javascripts %}

templates/file.html.j2
{% extends "base.html.j2" %}

{% block app %}
<div class="container">
    <div class="row align-items-center justify-content-center">
        <h1>File: {{ file.original_filename }}</h1>
    </div>
    <div class="row">
        <div class="col">
            <h1>Content</h1>
            <code>
{{ content }}
            </code>
        </div>
    </div>
</div>
{% endblock app %}

{% block title %}
{{ super() }}: File View
{% endblock title %}

templates/files.html.j2
{% extends "base.html.j2" %}

{% block app %}
<div class="container border rounded mt-2">
    <div class="row m-4">
        <form class="container-fluid p-2" action="{{url_for('main.files')}}" method="post" enctype="multipart/form-data">
                {{ form.csrf_token }}
                    <div class="row p-2 text-center">
                        <h1>Files</h1>
                    </div>
                    <div class="row text-center mb-1">
                            <input class="btn btn-sm btn-secondary" type="button" value="New File" data-bs-toggle="collapse" data-bs-target="#collapseNewFile">
                    </div>
                    <div class="row align-items-end p-2 collapse  border rounded" id="collapseNewFile">
                        <div class="col">
                            {{ form.label.label(class="form-label") }}
                            {{ form.label(class="form-control", value="untitled") }}
                            {% if form.label.errors %}
                                <ul class="rounded danger list-unstyled">
                                {% for error in form.label.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        <div class="col">
                            {{ form.file.label(class="form-label") }}
                            {{ form.file(class="form-control") }}
                            {% if form.file.errors %}
                                <ul class="rounded danger list-unstyled">
                                {% for error in form.file.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        <div class="col text-center">
                            <input class="btn btn-primary" type="submit" value="Upload">
                        </div>
                    </div>
        </form>
    </div>
    <div class="row p-2">
        <table class="table table-striped table-bordered">
            <thead>
                <th>Label</th>
                <th>File Name</th>
                <th>SHA-256 Hash</th>
                <th></th>
                <th></th>
            </thead>
            <tbody>
            {% for file in files %}
                <tr>
                    <td>{{ file.label }}</td>
                    <td>{{ file.original_filename }}</td>
                    <td>{{ file.sha256 }}</td>
                    <td><a href="{{url_for('main.file', id=file.id)}}" class="btn btn-sm btn-primary">View</a></td>
                    <td><form action="{{url_for('main.file_delete', id=file.id)}}" method="post"><button type="submit" class="btn btn-sm btn-danger">Delete</button></form></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock app %}

{% block title %}
{{ super() }}: Files
{% endblock title %}

templates/index.html.j2
{% extends "base.html.j2" %}

{% block app %}
<div class="container">
    <div class="row align-items-center justify-content-center">
        <div class="col text-center">
            <h1 class="display-5">Welcome to Squeezy</h1>
        </div>
    </div>
    <div class="row align-items-center justify-content-center text-right">
        <p>Welcome, {{ user.email }}! <a href="{{ url_for('main.logout')}}">Logout!</a></p>

    </div>
</div>
{% endblock app %}

templates/logs.html.j2
{% extends "base.html.j2" %}

{% block app %}
<div class="container">
    <div class="row align-items-center justify-content-center">
        <h1>Logs</h1>
    </div>
    <div class="row" id="status-widget-block">
        <div class="accordion" id="logAccordion">
            {% for key, value in logs.items() %}
            <div class="accordion-item">
                <h2 class="accordion-header" id="log_{{key}}">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#logCollapse_{{key}}" aria-expanded="true" aria-controls="logCollapse_{{key}}">
                        {{ key.capitalize() }} Log
                    </button>
                </h2>
                <div class="accordion-collapse collapse" id="logCollapse_{{key}}">
                    <div class="p-2">
                        <a class="btn btn-secondary" href="{{url_for('main.download_log', name=key)}}">Download</a>
                    </div>
                    <hr>
                    <div class="accordion-body">
                        <pre class="file-view">{{ value if value | length > 0 else "Empty" }}</pre>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock app %}

{% block title %}
{{ super() }}: Status
{% endblock title %}

templates/users.html.j2
{% extends "base.html.j2" %}

{% block app %}
<div class="container">
    <div class="row align-items-center justify-content-center">
        <h1>Users</h1>
    </div>
    <div class="row" id="status-widget-block">
        Work in progress
    </div>
</div>
{% endblock app %}

{% block title %}
{{ super() }}: Status
{% endblock title %}